--[[This file was generated by Galactic Private Dumper v1.7]]
local Players = game:GetService('Players')
local StarterGui = game:GetService('StarterGui')
local TeleportService = game:GetService('TeleportService')
local Workspace = game:GetService('Workspace')
local ReplicatedStorage = game:GetService('ReplicatedStorage')
local CoreGui = game:GetService('CoreGui')
local HttpService = game:GetService('HttpService')
local v9 = game.Players.LocalPlayer:WaitForChild("PlayerGui")
local v10 = ReplicatedStorage:WaitForChild("RemoteEvents")
local v11 = v10:WaitForChild("RequestTakeDiamonds")
local v12 = v9:WaitForChild("Interface")
local v13 = v12:WaitForChild("DiamondCount")
local v14 = v13:WaitForChild("Count")
task.spawn(function()
    local screengui_147 = Instance.new("ScreenGui")

    screengui_147.Name = "Autofarm Diamond Nagi Hub"
    screengui_147.Parent = CoreGui
    local frame_849 = Instance.new("Frame")

    frame_849.Parent = screengui_147
    frame_849.Size = UDim2.new(0, 250, 0, 340)
    frame_849.Position = UDim2.new(0, 80, 0, 20)
    frame_849.BackgroundColor3 = Color3.fromRGB(35, 35, 35)
    frame_849.BorderSizePixel = 0
    frame_849.Active = true
    frame_849.Draggable = true
    local uicorner_756 = Instance.new("UICorner")

    uicorner_756.CornerRadius = UDim.new(0, 8)
    uicorner_756.Parent = frame_849
    local uistroke_693 = Instance.new("UIStroke")

    uistroke_693.Thickness = 1.5
    uistroke_693.Color = Color3.fromRGB(8, 15, 2)
    uistroke_693.Parent = frame_849
    local textlabel_401 = Instance.new("TextLabel")

    textlabel_401.Parent = frame_849
    textlabel_401.Size = UDim2.new(1, 0, 0, 30)
    textlabel_401.BackgroundTransparency = 1
    textlabel_401.Text = "Autofarm Diamond Nagi Hub"
    textlabel_401.TextColor3 = Color3.fromRGB(255, 255, 255)
    textlabel_401.Font = Font.GothamBold
    textlabel_401.TextSize = 14
    textlabel_401.TextStrokeTransparency = 0.6
    local textlabel_518 = Instance.new("TextLabel")

    textlabel_518.Name = "StatusLabel"
    textlabel_518.Parent = frame_849
    textlabel_518.Size = UDim2.new(1, -20, 0, 35)
    textlabel_518.Position = UDim2.new(0, 10, 0, 40)
    textlabel_518.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
    textlabel_518.TextColor3 = Color3.fromRGB(1, 1, 1)
    textlabel_518.Font = Font.GothamBold
    textlabel_518.TextSize = 14
    textlabel_518.BorderSizePixel = 0
    textlabel_518.Text = "Status: Idle"
    local uicorner_384 = Instance.new("UICorner")

    uicorner_384.CornerRadius = UDim.new(0, 6)
    uicorner_384.Parent = textlabel_518
    local frame_590 = Instance.new("Frame")

    frame_590.Parent = frame_849
    frame_590.Position = UDim2.new(0, 10, 0, 80)
    frame_590.Size = UDim2.new(1, -20, 0, 250)
    frame_590.BackgroundColor3 = Color3.fromRGB(25, 25, 25)
    frame_590.BorderSizePixel = 0
    local uicorner_776 = Instance.new("UICorner")

    uicorner_776.CornerRadius = UDim.new(0, 6)
    uicorner_776.Parent = frame_590
    local textlabel_833 = Instance.new("TextLabel")

    textlabel_833.Parent = frame_590
    textlabel_833.Size = UDim2.new(1, -10, 0, 110)
    textlabel_833.Position = UDim2.new(0, 5, 0, 5)
    textlabel_833.BackgroundTransparency = 1
    textlabel_833.Text = "--------------------------------------------\
Soon:\
»Suggest features in the discord.\
--------------------------------------------\
Info:\
»Owner: Nagi Hub\
"
    textlabel_833.TextColor3 = Color3.fromRGB(255, 255, 255)
    textlabel_833.Font = Font.Gotham
    textlabel_833.TextSize = 13
    textlabel_833.TextWrapped = true
    textlabel_833.TextYAlignment = Enum.TextYAlignment.Top
    local textbutton_406 = Instance.new("TextButton")

    textbutton_406.Parent = frame_590
    textbutton_406.Size = UDim2.new(0, 150, 0, 30)
    textbutton_406.Position = UDim2.new(0.5, -75, 0, 115)
    textbutton_406.Text = "Copy Discord Link"
    textbutton_406.TextColor3 = Color3.fromRGB(1, 1, 1)
    textbutton_406.BackgroundColor3 = Color3.fromRGB(45, 45, 45)
    textbutton_406.Font = Font.GothamBold
    textbutton_406.TextSize = 14
    textbutton_406.AutoButtonColor = true
    local uicorner_327 = Instance.new("UICorner")

    uicorner_327.CornerRadius = UDim.new(0, 6)
    uicorner_327.Parent = textbutton_406
    textbutton_406.MouseButton1Click:Connect(function(arg1, arg2, arg3, arg4)
        setclipboard("https://discord.gg/MQAut7egGp")
        local v77 = StarterGui.SetCore(StarterGui, "SendNotification", {
    Duration = 4,
    Text = "Discord link copied to clipboard",
    Title = "Copied!"
})
    end)
    local textlabel_744 = Instance.new("TextLabel")

    textlabel_744.Parent = frame_590
    textlabel_744.Size = UDim2.new(1, -10, 0, 100)
    textlabel_744.Position = UDim2.new(0, 5, 0, 150)
    textlabel_744.BackgroundTransparency = 1
    textlabel_744.Text = "»If there is any bug please report it on discord\
»Thanks for testing this farm script\
»Enjoy farming diamonds!\
"
    textlabel_744.TextColor3 = Color3.fromRGB(255, 255, 255)
    textlabel_744.Font = Font.Gotham
    textlabel_744.TextSize = 13
    textlabel_744.TextWrapped = true
    textlabel_744.TextYAlignment = Enum.TextYAlignment.Top
end)
_G.sendNotification = function(arg1, arg2, arg3)
    local v1 = StarterGui.SetCore(StarterGui, "SendNotification", {
    Duration = arg3,
    Text = arg2,
    Title = arg1
})
end
_G.sendWebhook = function(arg1, arg2, arg3, arg4, arg5)
    local v1 = HttpService:JSONEncode({
    embeds = {
        {
            color = 65280,
            fields = {
                {
                    name = "Diamonds Collected",
                    value = "arg1",
                    inline = true
                },
                {
                    name = "Total Diamonds",
                    value = "v14.Text",
                    inline = true
                },
                {
                    name = "Source",
                    value = arg2,
                    inline = true
                }
            },
            footer = {
                text = "Nagi hub Farm Diamond Script"
            },
            title = "Farm Announcement"
        }
    }
})
    local v2 = HttpService.RequestAsync(HttpService, {
    Url = getgenv()["WebhookURL"],
    Body = v1,
    Headers = {
        ["Content-Type"] = "application/json"
    },
    Method = "POST"
})
end
_G.hopServer = function(arg1, arg2, arg3, arg4, arg5)
    local v1 = StarterGui.SetCore(StarterGui, "SendNotification", {
    Duration = 3,
    Text = "Attempting to find a new server...",
    Title = "Hopping Server"
})
    local v2 = TeleportService.Teleport(TeleportService, 131623223084840)
end
local v19 = StarterGui.SetCore(StarterGui, "SendNotification", {
    Duration = 3,
    Text = "Waiting for character to spawn...",
    Title = "Script Loaded"
})
local v20 = StarterGui.SetCore(StarterGui, "SendNotification", {
    Duration = 3,
    Text = "Searching for diamonds and chests...",
    Title = "Farming Started"
})
local v21 = StarterGui.SetCore(StarterGui, "SendNotification", {
    Duration = 5,
    Text = "Scheduled to hop server in 20 seconds.",
    Title = "Server Hop"
})
task.delay(20, function()
    local v1 = StarterGui.SetCore(StarterGui, "SendNotification", {
    Duration = 3,
    Text = "Initiating automatic server hop.",
    Title = "Scheduled Hop"
})
    local v2 = StarterGui.SetCore(StarterGui, "SendNotification", {
    Duration = 3,
    Text = "Attempting to find a new server...",
    Title = "Hopping Server"
})
    local v3 = TeleportService.Teleport(TeleportService, 131623223084840)
end)
task.wait(1)
local v24 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v25 = Workspace:GetDescendants()
local v26 = Workspace.Items:GetChildren()
local v27 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v28 = v27.GetPivot(v27)
v24.CFrame = v28
v24.Anchored = true
task.wait(0.1)
local v32 = v27:FindFirstChild("Main")
local v33 = v32:FindFirstChild("ProximityAttachment")
local v34 = v33:FindFirstChild("ProximityInteraction")
tick()
v24.Anchored = false
v24.CFrame = v24.CFrame
task.wait(1)
local v39 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v40 = Workspace:GetDescendants()
local v41 = Workspace.Items:GetChildren()
local v42 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v43 = v42.GetPivot(v42)
v39.CFrame = v43
v39.Anchored = true
task.wait(0.1)
local v47 = v42:FindFirstChild("Main")
local v48 = v47:FindFirstChild("ProximityAttachment")
local v49 = v48:FindFirstChild("ProximityInteraction")
tick()
v39.Anchored = false
v39.CFrame = v39.CFrame
task.wait(1)
local v54 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v55 = Workspace:GetDescendants()
local v56 = Workspace.Items:GetChildren()
local v57 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v58 = v57.GetPivot(v57)
v54.CFrame = v58
v54.Anchored = true
task.wait(0.1)
local v62 = v57:FindFirstChild("Main")
local v63 = v62:FindFirstChild("ProximityAttachment")
local v64 = v63:FindFirstChild("ProximityInteraction")
tick()
v54.Anchored = false
v54.CFrame = v54.CFrame
task.wait(1)
local v69 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v70 = Workspace:GetDescendants()
local v71 = Workspace.Items:GetChildren()
local v72 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v73 = v72.GetPivot(v72)
v69.CFrame = v73
v69.Anchored = true
task.wait(0.1)
local v77 = v72:FindFirstChild("Main")
local v78 = v77:FindFirstChild("ProximityAttachment")
local v79 = v78:FindFirstChild("ProximityInteraction")
tick()
v69.Anchored = false
v69.CFrame = v69.CFrame
task.wait(1)
local v84 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v85 = Workspace:GetDescendants()
local v86 = Workspace.Items:GetChildren()
local v87 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v88 = v87.GetPivot(v87)
v84.CFrame = v88
v84.Anchored = true
task.wait(0.1)
local v92 = v87:FindFirstChild("Main")
local v93 = v92:FindFirstChild("ProximityAttachment")
local v94 = v93:FindFirstChild("ProximityInteraction")
tick()
v84.Anchored = false
v84.CFrame = v84.CFrame
task.wait(1)
local v99 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v100 = Workspace:GetDescendants()
local v101 = Workspace.Items:GetChildren()
local v102 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v103 = v102.GetPivot(v102)
v99.CFrame = v103
v99.Anchored = true
task.wait(0.1)
local v107 = v102:FindFirstChild("Main")
local v108 = v107:FindFirstChild("ProximityAttachment")
local v109 = v108:FindFirstChild("ProximityInteraction")
tick()
v99.Anchored = false
v99.CFrame = v99.CFrame
task.wait(1)
local v114 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v115 = Workspace:GetDescendants()
local v116 = Workspace.Items:GetChildren()
local v117 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v118 = v117.GetPivot(v117)
v114.CFrame = v118
v114.Anchored = true
task.wait(0.1)
local v122 = v117:FindFirstChild("Main")
local v123 = v122:FindFirstChild("ProximityAttachment")
local v124 = v123:FindFirstChild("ProximityInteraction")
tick()
v114.Anchored = false
v114.CFrame = v114.CFrame
task.wait(1)
local v129 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v130 = Workspace:GetDescendants()
local v131 = Workspace.Items:GetChildren()
local v132 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v133 = v132.GetPivot(v132)
v129.CFrame = v133
v129.Anchored = true
task.wait(0.1)
local v137 = v132:FindFirstChild("Main")
local v138 = v137:FindFirstChild("ProximityAttachment")
local v139 = v138:FindFirstChild("ProximityInteraction")
tick()
v129.Anchored = false
v129.CFrame = v129.CFrame
task.wait(1)
local v144 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v145 = Workspace:GetDescendants()
local v146 = Workspace.Items:GetChildren()
local v147 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v148 = v147.GetPivot(v147)
v144.CFrame = v148
v144.Anchored = true
task.wait(0.1)
local v152 = v147:FindFirstChild("Main")
local v153 = v152:FindFirstChild("ProximityAttachment")
local v154 = v153:FindFirstChild("ProximityInteraction")
tick()
v144.Anchored = false
v144.CFrame = v144.CFrame
task.wait(1)
local v159 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v160 = Workspace:GetDescendants()
local v161 = Workspace.Items:GetChildren()
local v162 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v163 = v162.GetPivot(v162)
v159.CFrame = v163
v159.Anchored = true
task.wait(0.1)
local v167 = v162:FindFirstChild("Main")
local v168 = v167:FindFirstChild("ProximityAttachment")
local v169 = v168:FindFirstChild("ProximityInteraction")
tick()
v159.Anchored = false
v159.CFrame = v159.CFrame
task.wait(1)
local v174 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v175 = Workspace:GetDescendants()
local v176 = Workspace.Items:GetChildren()
local v177 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v178 = v177.GetPivot(v177)
v174.CFrame = v178
v174.Anchored = true
task.wait(0.1)
local v182 = v177:FindFirstChild("Main")
local v183 = v182:FindFirstChild("ProximityAttachment")
local v184 = v183:FindFirstChild("ProximityInteraction")
tick()
v174.Anchored = false
v174.CFrame = v174.CFrame
task.wait(1)
local v189 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v190 = Workspace:GetDescendants()
local v191 = Workspace.Items:GetChildren()
local v192 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v193 = v192.GetPivot(v192)
v189.CFrame = v193
v189.Anchored = true
task.wait(0.1)
local v197 = v192:FindFirstChild("Main")
local v198 = v197:FindFirstChild("ProximityAttachment")
local v199 = v198:FindFirstChild("ProximityInteraction")
tick()
v189.Anchored = false
v189.CFrame = v189.CFrame
task.wait(1)
local v204 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v205 = Workspace:GetDescendants()
local v206 = Workspace.Items:GetChildren()
local v207 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v208 = v207.GetPivot(v207)
v204.CFrame = v208
v204.Anchored = true
task.wait(0.1)
local v212 = v207:FindFirstChild("Main")
local v213 = v212:FindFirstChild("ProximityAttachment")
local v214 = v213:FindFirstChild("ProximityInteraction")
tick()
v204.Anchored = false
v204.CFrame = v204.CFrame
task.wait(1)
local v219 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v220 = Workspace:GetDescendants()
local v221 = Workspace.Items:GetChildren()
local v222 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v223 = v222.GetPivot(v222)
v219.CFrame = v223
v219.Anchored = true
task.wait(0.1)
local v227 = v222:FindFirstChild("Main")
local v228 = v227:FindFirstChild("ProximityAttachment")
local v229 = v228:FindFirstChild("ProximityInteraction")
tick()
v219.Anchored = false
v219.CFrame = v219.CFrame
task.wait(1)
local v234 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v235 = Workspace:GetDescendants()
local v236 = Workspace.Items:GetChildren()
local v237 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v238 = v237.GetPivot(v237)
v234.CFrame = v238
v234.Anchored = true
task.wait(0.1)
local v242 = v237:FindFirstChild("Main")
local v243 = v242:FindFirstChild("ProximityAttachment")
local v244 = v243:FindFirstChild("ProximityInteraction")
tick()
v234.Anchored = false
v234.CFrame = v234.CFrame
task.wait(1)
local v249 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v250 = Workspace:GetDescendants()
local v251 = Workspace.Items:GetChildren()
local v252 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v253 = v252.GetPivot(v252)
v249.CFrame = v253
v249.Anchored = true
task.wait(0.1)
local v257 = v252:FindFirstChild("Main")
local v258 = v257:FindFirstChild("ProximityAttachment")
local v259 = v258:FindFirstChild("ProximityInteraction")
tick()
v249.Anchored = false
v249.CFrame = v249.CFrame
task.wait(1)
local v264 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v265 = Workspace:GetDescendants()
local v266 = Workspace.Items:GetChildren()
local v267 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v268 = v267.GetPivot(v267)
v264.CFrame = v268
v264.Anchored = true
task.wait(0.1)
local v272 = v267:FindFirstChild("Main")
local v273 = v272:FindFirstChild("ProximityAttachment")
local v274 = v273:FindFirstChild("ProximityInteraction")
tick()
v264.Anchored = false
v264.CFrame = v264.CFrame
task.wait(1)
local v279 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v280 = Workspace:GetDescendants()
local v281 = Workspace.Items:GetChildren()
local v282 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v283 = v282.GetPivot(v282)
v279.CFrame = v283
v279.Anchored = true
task.wait(0.1)
local v287 = v282:FindFirstChild("Main")
local v288 = v287:FindFirstChild("ProximityAttachment")
local v289 = v288:FindFirstChild("ProximityInteraction")
tick()
v279.Anchored = false
v279.CFrame = v279.CFrame
task.wait(1)
local v294 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v295 = Workspace:GetDescendants()
local v296 = Workspace.Items:GetChildren()
local v297 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v298 = v297.GetPivot(v297)
v294.CFrame = v298
v294.Anchored = true
task.wait(0.1)
local v302 = v297:FindFirstChild("Main")
local v303 = v302:FindFirstChild("ProximityAttachment")
local v304 = v303:FindFirstChild("ProximityInteraction")
tick()
v294.Anchored = false
v294.CFrame = v294.CFrame
task.wait(1)
local v309 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v310 = Workspace:GetDescendants()
local v311 = Workspace.Items:GetChildren()
local v312 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v313 = v312.GetPivot(v312)
v309.CFrame = v313
v309.Anchored = true
task.wait(0.1)
local v317 = v312:FindFirstChild("Main")
local v318 = v317:FindFirstChild("ProximityAttachment")
local v319 = v318:FindFirstChild("ProximityInteraction")
tick()
v309.Anchored = false
v309.CFrame = v309.CFrame
task.wait(1)
local v324 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v325 = Workspace:GetDescendants()
local v326 = Workspace.Items:GetChildren()
local v327 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v328 = v327.GetPivot(v327)
v324.CFrame = v328
v324.Anchored = true
task.wait(0.1)
local v332 = v327:FindFirstChild("Main")
local v333 = v332:FindFirstChild("ProximityAttachment")
local v334 = v333:FindFirstChild("ProximityInteraction")
tick()
v324.Anchored = false
v324.CFrame = v324.CFrame
task.wait(1)
local v339 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v340 = Workspace:GetDescendants()
local v341 = Workspace.Items:GetChildren()
local v342 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v343 = v342.GetPivot(v342)
v339.CFrame = v343
v339.Anchored = true
task.wait(0.1)
local v347 = v342:FindFirstChild("Main")
local v348 = v347:FindFirstChild("ProximityAttachment")
local v349 = v348:FindFirstChild("ProximityInteraction")
tick()
v339.Anchored = false
v339.CFrame = v339.CFrame
task.wait(1)
local v354 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v355 = Workspace:GetDescendants()
local v356 = Workspace.Items:GetChildren()
local v357 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v358 = v357.GetPivot(v357)
v354.CFrame = v358
v354.Anchored = true
task.wait(0.1)
local v362 = v357:FindFirstChild("Main")
local v363 = v362:FindFirstChild("ProximityAttachment")
local v364 = v363:FindFirstChild("ProximityInteraction")
tick()
v354.Anchored = false
v354.CFrame = v354.CFrame
task.wait(1)
local v369 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v370 = Workspace:GetDescendants()
local v371 = Workspace.Items:GetChildren()
local v372 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v373 = v372.GetPivot(v372)
v369.CFrame = v373
v369.Anchored = true
task.wait(0.1)
local v377 = v372:FindFirstChild("Main")
local v378 = v377:FindFirstChild("ProximityAttachment")
local v379 = v378:FindFirstChild("ProximityInteraction")
tick()
v369.Anchored = false
v369.CFrame = v369.CFrame
task.wait(1)
local v384 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v385 = Workspace:GetDescendants()
local v386 = Workspace.Items:GetChildren()
local v387 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v388 = v387.GetPivot(v387)
v384.CFrame = v388
v384.Anchored = true
task.wait(0.1)
local v392 = v387:FindFirstChild("Main")
local v393 = v392:FindFirstChild("ProximityAttachment")
local v394 = v393:FindFirstChild("ProximityInteraction")
tick()
v384.Anchored = false
v384.CFrame = v384.CFrame
task.wait(1)
local v399 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v400 = Workspace:GetDescendants()
local v401 = Workspace.Items:GetChildren()
local v402 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v403 = v402.GetPivot(v402)
v399.CFrame = v403
v399.Anchored = true
task.wait(0.1)
local v407 = v402:FindFirstChild("Main")
local v408 = v407:FindFirstChild("ProximityAttachment")
local v409 = v408:FindFirstChild("ProximityInteraction")
tick()
v399.Anchored = false
v399.CFrame = v399.CFrame
task.wait(1)
local v414 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v415 = Workspace:GetDescendants()
local v416 = Workspace.Items:GetChildren()
local v417 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v418 = v417.GetPivot(v417)
v414.CFrame = v418
v414.Anchored = true
task.wait(0.1)
local v422 = v417:FindFirstChild("Main")
local v423 = v422:FindFirstChild("ProximityAttachment")
local v424 = v423:FindFirstChild("ProximityInteraction")
tick()
v414.Anchored = false
v414.CFrame = v414.CFrame
task.wait(1)
local v429 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v430 = Workspace:GetDescendants()
local v431 = Workspace.Items:GetChildren()
local v432 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v433 = v432.GetPivot(v432)
v429.CFrame = v433
v429.Anchored = true
task.wait(0.1)
local v437 = v432:FindFirstChild("Main")
local v438 = v437:FindFirstChild("ProximityAttachment")
local v439 = v438:FindFirstChild("ProximityInteraction")
tick()
v429.Anchored = false
v429.CFrame = v429.CFrame
task.wait(1)
local v444 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v445 = Workspace:GetDescendants()
local v446 = Workspace.Items:GetChildren()
local v447 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v448 = v447.GetPivot(v447)
v444.CFrame = v448
v444.Anchored = true
task.wait(0.1)
local v452 = v447:FindFirstChild("Main")
local v453 = v452:FindFirstChild("ProximityAttachment")
local v454 = v453:FindFirstChild("ProximityInteraction")
tick()
v444.Anchored = false
v444.CFrame = v444.CFrame
task.wait(1)
local v459 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v460 = Workspace:GetDescendants()
local v461 = Workspace.Items:GetChildren()
local v462 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v463 = v462.GetPivot(v462)
v459.CFrame = v463
v459.Anchored = true
task.wait(0.1)
local v467 = v462:FindFirstChild("Main")
local v468 = v467:FindFirstChild("ProximityAttachment")
local v469 = v468:FindFirstChild("ProximityInteraction")
tick()
v459.Anchored = false
v459.CFrame = v459.CFrame
task.wait(1)
local v474 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v475 = Workspace:GetDescendants()
local v476 = Workspace.Items:GetChildren()
local v477 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v478 = v477.GetPivot(v477)
v474.CFrame = v478
v474.Anchored = true
task.wait(0.1)
local v482 = v477:FindFirstChild("Main")
local v483 = v482:FindFirstChild("ProximityAttachment")
local v484 = v483:FindFirstChild("ProximityInteraction")
tick()
v474.Anchored = false
v474.CFrame = v474.CFrame
task.wait(1)
local v489 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v490 = Workspace:GetDescendants()
local v491 = Workspace.Items:GetChildren()
local v492 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v493 = v492.GetPivot(v492)
v489.CFrame = v493
v489.Anchored = true
task.wait(0.1)
local v497 = v492:FindFirstChild("Main")
local v498 = v497:FindFirstChild("ProximityAttachment")
local v499 = v498:FindFirstChild("ProximityInteraction")
tick()
v489.Anchored = false
v489.CFrame = v489.CFrame
task.wait(1)
local v504 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v505 = Workspace:GetDescendants()
local v506 = Workspace.Items:GetChildren()
local v507 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v508 = v507.GetPivot(v507)
v504.CFrame = v508
v504.Anchored = true
task.wait(0.1)
local v512 = v507:FindFirstChild("Main")
local v513 = v512:FindFirstChild("ProximityAttachment")
local v514 = v513:FindFirstChild("ProximityInteraction")
tick()
v504.Anchored = false
v504.CFrame = v504.CFrame
task.wait(1)
local v519 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v520 = Workspace:GetDescendants()
local v521 = Workspace.Items:GetChildren()
local v522 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v523 = v522.GetPivot(v522)
v519.CFrame = v523
v519.Anchored = true
task.wait(0.1)
local v527 = v522:FindFirstChild("Main")
local v528 = v527:FindFirstChild("ProximityAttachment")
local v529 = v528:FindFirstChild("ProximityInteraction")
tick()
v519.Anchored = false
v519.CFrame = v519.CFrame
task.wait(1)
local v534 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v535 = Workspace:GetDescendants()
local v536 = Workspace.Items:GetChildren()
local v537 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v538 = v537.GetPivot(v537)
v534.CFrame = v538
v534.Anchored = true
task.wait(0.1)
local v542 = v537:FindFirstChild("Main")
local v543 = v542:FindFirstChild("ProximityAttachment")
local v544 = v543:FindFirstChild("ProximityInteraction")
tick()
v534.Anchored = false
v534.CFrame = v534.CFrame
task.wait(1)
local v549 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v550 = Workspace:GetDescendants()
local v551 = Workspace.Items:GetChildren()
local v552 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v553 = v552.GetPivot(v552)
v549.CFrame = v553
v549.Anchored = true
task.wait(0.1)
local v557 = v552:FindFirstChild("Main")
local v558 = v557:FindFirstChild("ProximityAttachment")
local v559 = v558:FindFirstChild("ProximityInteraction")
tick()
v549.Anchored = false
v549.CFrame = v549.CFrame
task.wait(1)
local v564 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v565 = Workspace:GetDescendants()
local v566 = Workspace.Items:GetChildren()
local v567 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v568 = v567.GetPivot(v567)
v564.CFrame = v568
v564.Anchored = true
task.wait(0.1)
local v572 = v567:FindFirstChild("Main")
local v573 = v572:FindFirstChild("ProximityAttachment")
local v574 = v573:FindFirstChild("ProximityInteraction")
tick()
v564.Anchored = false
v564.CFrame = v564.CFrame
task.wait(1)
local v579 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v580 = Workspace:GetDescendants()
local v581 = Workspace.Items:GetChildren()
local v582 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v583 = v582.GetPivot(v582)
v579.CFrame = v583
v579.Anchored = true
task.wait(0.1)
local v587 = v582:FindFirstChild("Main")
local v588 = v587:FindFirstChild("ProximityAttachment")
local v589 = v588:FindFirstChild("ProximityInteraction")
tick()
v579.Anchored = false
v579.CFrame = v579.CFrame
task.wait(1)
local v594 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v595 = Workspace:GetDescendants()
local v596 = Workspace.Items:GetChildren()
local v597 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v598 = v597.GetPivot(v597)
v594.CFrame = v598
v594.Anchored = true
task.wait(0.1)
local v602 = v597:FindFirstChild("Main")
local v603 = v602:FindFirstChild("ProximityAttachment")
local v604 = v603:FindFirstChild("ProximityInteraction")
tick()
v594.Anchored = false
v594.CFrame = v594.CFrame
task.wait(1)
local v609 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v610 = Workspace:GetDescendants()
local v611 = Workspace.Items:GetChildren()
local v612 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v613 = v612.GetPivot(v612)
v609.CFrame = v613
v609.Anchored = true
task.wait(0.1)
local v617 = v612:FindFirstChild("Main")
local v618 = v617:FindFirstChild("ProximityAttachment")
local v619 = v618:FindFirstChild("ProximityInteraction")
tick()
v609.Anchored = false
v609.CFrame = v609.CFrame
task.wait(1)
local v624 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v625 = Workspace:GetDescendants()
local v626 = Workspace.Items:GetChildren()
local v627 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v628 = v627.GetPivot(v627)
v624.CFrame = v628
v624.Anchored = true
task.wait(0.1)
local v632 = v627:FindFirstChild("Main")
local v633 = v632:FindFirstChild("ProximityAttachment")
local v634 = v633:FindFirstChild("ProximityInteraction")
tick()
v624.Anchored = false
v624.CFrame = v624.CFrame
task.wait(1)
local v639 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v640 = Workspace:GetDescendants()
local v641 = Workspace.Items:GetChildren()
local v642 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v643 = v642.GetPivot(v642)
v639.CFrame = v643
v639.Anchored = true
task.wait(0.1)
local v647 = v642:FindFirstChild("Main")
local v648 = v647:FindFirstChild("ProximityAttachment")
local v649 = v648:FindFirstChild("ProximityInteraction")
tick()
v639.Anchored = false
v639.CFrame = v639.CFrame
task.wait(1)
local v654 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v655 = Workspace:GetDescendants()
local v656 = Workspace.Items:GetChildren()
local v657 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v658 = v657.GetPivot(v657)
v654.CFrame = v658
v654.Anchored = true
task.wait(0.1)
local v662 = v657:FindFirstChild("Main")
local v663 = v662:FindFirstChild("ProximityAttachment")
local v664 = v663:FindFirstChild("ProximityInteraction")
tick()
v654.Anchored = false
v654.CFrame = v654.CFrame
task.wait(1)
local v669 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v670 = Workspace:GetDescendants()
local v671 = Workspace.Items:GetChildren()
local v672 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v673 = v672.GetPivot(v672)
v669.CFrame = v673
v669.Anchored = true
task.wait(0.1)
local v677 = v672:FindFirstChild("Main")
local v678 = v677:FindFirstChild("ProximityAttachment")
local v679 = v678:FindFirstChild("ProximityInteraction")
tick()
v669.Anchored = false
v669.CFrame = v669.CFrame
task.wait(1)
local v684 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v685 = Workspace:GetDescendants()
local v686 = Workspace.Items:GetChildren()
local v687 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v688 = v687.GetPivot(v687)
v684.CFrame = v688
v684.Anchored = true
task.wait(0.1)
local v692 = v687:FindFirstChild("Main")
local v693 = v692:FindFirstChild("ProximityAttachment")
local v694 = v693:FindFirstChild("ProximityInteraction")
tick()
v684.Anchored = false
v684.CFrame = v684.CFrame
task.wait(1)
local v699 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v700 = Workspace:GetDescendants()
local v701 = Workspace.Items:GetChildren()
local v702 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v703 = v702.GetPivot(v702)
v699.CFrame = v703
v699.Anchored = true
task.wait(0.1)
local v707 = v702:FindFirstChild("Main")
local v708 = v707:FindFirstChild("ProximityAttachment")
local v709 = v708:FindFirstChild("ProximityInteraction")
tick()
v699.Anchored = false
v699.CFrame = v699.CFrame
task.wait(1)
local v714 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v715 = Workspace:GetDescendants()
local v716 = Workspace.Items:GetChildren()
local v717 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v718 = v717.GetPivot(v717)
v714.CFrame = v718
v714.Anchored = true
task.wait(0.1)
local v722 = v717:FindFirstChild("Main")
local v723 = v722:FindFirstChild("ProximityAttachment")
local v724 = v723:FindFirstChild("ProximityInteraction")
tick()
v714.Anchored = false
v714.CFrame = v714.CFrame
task.wait(1)
local v729 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v730 = Workspace:GetDescendants()
local v731 = Workspace.Items:GetChildren()
local v732 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v733 = v732.GetPivot(v732)
v729.CFrame = v733
v729.Anchored = true
task.wait(0.1)
local v737 = v732:FindFirstChild("Main")
local v738 = v737:FindFirstChild("ProximityAttachment")
local v739 = v738:FindFirstChild("ProximityInteraction")
tick()
v729.Anchored = false
v729.CFrame = v729.CFrame
task.wait(1)
local v744 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v745 = Workspace:GetDescendants()
local v746 = Workspace.Items:GetChildren()
local v747 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v748 = v747.GetPivot(v747)
v744.CFrame = v748
v744.Anchored = true
task.wait(0.1)
local v752 = v747:FindFirstChild("Main")
local v753 = v752:FindFirstChild("ProximityAttachment")
local v754 = v753:FindFirstChild("ProximityInteraction")
tick()
v744.Anchored = false
v744.CFrame = v744.CFrame
task.wait(1)
local v759 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v760 = Workspace:GetDescendants()
local v761 = Workspace.Items:GetChildren()
local v762 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v763 = v762.GetPivot(v762)
v759.CFrame = v763
v759.Anchored = true
task.wait(0.1)
local v767 = v762:FindFirstChild("Main")
local v768 = v767:FindFirstChild("ProximityAttachment")
local v769 = v768:FindFirstChild("ProximityInteraction")
tick()
v759.Anchored = false
v759.CFrame = v759.CFrame
task.wait(1)
local v774 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v775 = Workspace:GetDescendants()
local v776 = Workspace.Items:GetChildren()
local v777 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v778 = v777.GetPivot(v777)
v774.CFrame = v778
v774.Anchored = true
task.wait(0.1)
local v782 = v777:FindFirstChild("Main")
local v783 = v782:FindFirstChild("ProximityAttachment")
local v784 = v783:FindFirstChild("ProximityInteraction")
tick()
v774.Anchored = false
v774.CFrame = v774.CFrame
task.wait(1)
local v789 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v790 = Workspace:GetDescendants()
local v791 = Workspace.Items:GetChildren()
local v792 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v793 = v792.GetPivot(v792)
v789.CFrame = v793
v789.Anchored = true
task.wait(0.1)
local v797 = v792:FindFirstChild("Main")
local v798 = v797:FindFirstChild("ProximityAttachment")
local v799 = v798:FindFirstChild("ProximityInteraction")
tick()
v789.Anchored = false
v789.CFrame = v789.CFrame
task.wait(1)
local v804 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v805 = Workspace:GetDescendants()
local v806 = Workspace.Items:GetChildren()
local v807 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v808 = v807.GetPivot(v807)
v804.CFrame = v808
v804.Anchored = true
task.wait(0.1)
local v812 = v807:FindFirstChild("Main")
local v813 = v812:FindFirstChild("ProximityAttachment")
local v814 = v813:FindFirstChild("ProximityInteraction")
tick()
v804.Anchored = false
v804.CFrame = v804.CFrame
task.wait(1)
local v819 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v820 = Workspace:GetDescendants()
local v821 = Workspace.Items:GetChildren()
local v822 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v823 = v822.GetPivot(v822)
v819.CFrame = v823
v819.Anchored = true
task.wait(0.1)
local v827 = v822:FindFirstChild("Main")
local v828 = v827:FindFirstChild("ProximityAttachment")
local v829 = v828:FindFirstChild("ProximityInteraction")
tick()
v819.Anchored = false
v819.CFrame = v819.CFrame
task.wait(1)
local v834 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v835 = Workspace:GetDescendants()
local v836 = Workspace.Items:GetChildren()
local v837 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v838 = v837.GetPivot(v837)
v834.CFrame = v838
v834.Anchored = true
task.wait(0.1)
local v842 = v837:FindFirstChild("Main")
local v843 = v842:FindFirstChild("ProximityAttachment")
local v844 = v843:FindFirstChild("ProximityInteraction")
tick()
v834.Anchored = false
v834.CFrame = v834.CFrame
task.wait(1)
local v849 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v850 = Workspace:GetDescendants()
local v851 = Workspace.Items:GetChildren()
local v852 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v853 = v852.GetPivot(v852)
v849.CFrame = v853
v849.Anchored = true
task.wait(0.1)
local v857 = v852:FindFirstChild("Main")
local v858 = v857:FindFirstChild("ProximityAttachment")
local v859 = v858:FindFirstChild("ProximityInteraction")
tick()
v849.Anchored = false
v849.CFrame = v849.CFrame
task.wait(1)
local v864 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v865 = Workspace:GetDescendants()
local v866 = Workspace.Items:GetChildren()
local v867 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v868 = v867.GetPivot(v867)
v864.CFrame = v868
v864.Anchored = true
task.wait(0.1)
local v872 = v867:FindFirstChild("Main")
local v873 = v872:FindFirstChild("ProximityAttachment")
local v874 = v873:FindFirstChild("ProximityInteraction")
tick()
v864.Anchored = false
v864.CFrame = v864.CFrame
task.wait(1)
local v879 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v880 = Workspace:GetDescendants()
local v881 = Workspace.Items:GetChildren()
local v882 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v883 = v882.GetPivot(v882)
v879.CFrame = v883
v879.Anchored = true
task.wait(0.1)
local v887 = v882:FindFirstChild("Main")
local v888 = v887:FindFirstChild("ProximityAttachment")
local v889 = v888:FindFirstChild("ProximityInteraction")
tick()
v879.Anchored = false
v879.CFrame = v879.CFrame
task.wait(1)
local v894 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v895 = Workspace:GetDescendants()
local v896 = Workspace.Items:GetChildren()
local v897 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v898 = v897.GetPivot(v897)
v894.CFrame = v898
v894.Anchored = true
task.wait(0.1)
local v902 = v897:FindFirstChild("Main")
local v903 = v902:FindFirstChild("ProximityAttachment")
local v904 = v903:FindFirstChild("ProximityInteraction")
tick()
v894.Anchored = false
v894.CFrame = v894.CFrame
task.wait(1)
local v909 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v910 = Workspace:GetDescendants()
local v911 = Workspace.Items:GetChildren()
local v912 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v913 = v912.GetPivot(v912)
v909.CFrame = v913
v909.Anchored = true
task.wait(0.1)
local v917 = v912:FindFirstChild("Main")
local v918 = v917:FindFirstChild("ProximityAttachment")
local v919 = v918:FindFirstChild("ProximityInteraction")
tick()
v909.Anchored = false
v909.CFrame = v909.CFrame
task.wait(1)
local v924 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v925 = Workspace:GetDescendants()
local v926 = Workspace.Items:GetChildren()
local v927 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v928 = v927.GetPivot(v927)
v924.CFrame = v928
v924.Anchored = true
task.wait(0.1)
local v932 = v927:FindFirstChild("Main")
local v933 = v932:FindFirstChild("ProximityAttachment")
local v934 = v933:FindFirstChild("ProximityInteraction")
tick()
v924.Anchored = false
v924.CFrame = v924.CFrame
task.wait(1)
local v939 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v940 = Workspace:GetDescendants()
local v941 = Workspace.Items:GetChildren()
local v942 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v943 = v942.GetPivot(v942)
v939.CFrame = v943
v939.Anchored = true
task.wait(0.1)
local v947 = v942:FindFirstChild("Main")
local v948 = v947:FindFirstChild("ProximityAttachment")
local v949 = v948:FindFirstChild("ProximityInteraction")
tick()
v939.Anchored = false
v939.CFrame = v939.CFrame
task.wait(1)
local v954 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v955 = Workspace:GetDescendants()
local v956 = Workspace.Items:GetChildren()
local v957 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v958 = v957.GetPivot(v957)
v954.CFrame = v958
v954.Anchored = true
task.wait(0.1)
local v962 = v957:FindFirstChild("Main")
local v963 = v962:FindFirstChild("ProximityAttachment")
local v964 = v963:FindFirstChild("ProximityInteraction")
tick()
v954.Anchored = false
v954.CFrame = v954.CFrame
task.wait(1)
local v969 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v970 = Workspace:GetDescendants()
local v971 = Workspace.Items:GetChildren()
local v972 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v973 = v972.GetPivot(v972)
v969.CFrame = v973
v969.Anchored = true
task.wait(0.1)
local v977 = v972:FindFirstChild("Main")
local v978 = v977:FindFirstChild("ProximityAttachment")
local v979 = v978:FindFirstChild("ProximityInteraction")
tick()
v969.Anchored = false
v969.CFrame = v969.CFrame
task.wait(1)
local v984 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v985 = Workspace:GetDescendants()
local v986 = Workspace.Items:GetChildren()
local v987 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v988 = v987.GetPivot(v987)
v984.CFrame = v988
v984.Anchored = true
task.wait(0.1)
local v992 = v987:FindFirstChild("Main")
local v993 = v992:FindFirstChild("ProximityAttachment")
local v994 = v993:FindFirstChild("ProximityInteraction")
tick()
v984.Anchored = false
v984.CFrame = v984.CFrame
task.wait(1)
local v999 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v1000 = Workspace:GetDescendants()
local v1001 = Workspace.Items:GetChildren()
local v1002 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v1003 = v1002.GetPivot(v1002)
v999.CFrame = v1003
v999.Anchored = true
task.wait(0.1)
local v1007 = v1002:FindFirstChild("Main")
local v1008 = v1007:FindFirstChild("ProximityAttachment")
local v1009 = v1008:FindFirstChild("ProximityInteraction")
tick()
v999.Anchored = false
v999.CFrame = v999.CFrame
task.wait(1)
local v1014 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v1015 = Workspace:GetDescendants()
local v1016 = Workspace.Items:GetChildren()
local v1017 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v1018 = v1017.GetPivot(v1017)
v1014.CFrame = v1018
v1014.Anchored = true
task.wait(0.1)
local v1022 = v1017:FindFirstChild("Main")
local v1023 = v1022:FindFirstChild("ProximityAttachment")
local v1024 = v1023:FindFirstChild("ProximityInteraction")
tick()
v1014.Anchored = false
v1014.CFrame = v1014.CFrame
task.wait(1)
local v1029 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v1030 = Workspace:GetDescendants()
local v1031 = Workspace.Items:GetChildren()
local v1032 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v1033 = v1032.GetPivot(v1032)
v1029.CFrame = v1033
v1029.Anchored = true
task.wait(0.1)
local v1037 = v1032:FindFirstChild("Main")
local v1038 = v1037:FindFirstChild("ProximityAttachment")
local v1039 = v1038:FindFirstChild("ProximityInteraction")
tick()
v1029.Anchored = false
v1029.CFrame = v1029.CFrame
task.wait(1)
local v1044 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v1045 = Workspace:GetDescendants()
local v1046 = Workspace.Items:GetChildren()
local v1047 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v1048 = v1047.GetPivot(v1047)
v1044.CFrame = v1048
v1044.Anchored = true
task.wait(0.1)
local v1052 = v1047:FindFirstChild("Main")
local v1053 = v1052:FindFirstChild("ProximityAttachment")
local v1054 = v1053:FindFirstChild("ProximityInteraction")
tick()
v1044.Anchored = false
v1044.CFrame = v1044.CFrame
task.wait(1)
local v1059 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v1060 = Workspace:GetDescendants()
local v1061 = Workspace.Items:GetChildren()
local v1062 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v1063 = v1062.GetPivot(v1062)
v1059.CFrame = v1063
v1059.Anchored = true
task.wait(0.1)
local v1067 = v1062:FindFirstChild("Main")
local v1068 = v1067:FindFirstChild("ProximityAttachment")
local v1069 = v1068:FindFirstChild("ProximityInteraction")
tick()
v1059.Anchored = false
v1059.CFrame = v1059.CFrame
task.wait(1)
local v1074 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v1075 = Workspace:GetDescendants()
local v1076 = Workspace.Items:GetChildren()
local v1077 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v1078 = v1077.GetPivot(v1077)
v1074.CFrame = v1078
v1074.Anchored = true
task.wait(0.1)
local v1082 = v1077:FindFirstChild("Main")
local v1083 = v1082:FindFirstChild("ProximityAttachment")
local v1084 = v1083:FindFirstChild("ProximityInteraction")
tick()
v1074.Anchored = false
v1074.CFrame = v1074.CFrame
task.wait(1)
local v1089 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v1090 = Workspace:GetDescendants()
local v1091 = Workspace.Items:GetChildren()
local v1092 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v1093 = v1092.GetPivot(v1092)
v1089.CFrame = v1093
v1089.Anchored = true
task.wait(0.1)
local v1097 = v1092:FindFirstChild("Main")
local v1098 = v1097:FindFirstChild("ProximityAttachment")
local v1099 = v1098:FindFirstChild("ProximityInteraction")
tick()
v1089.Anchored = false
v1089.CFrame = v1089.CFrame
task.wait(1)
local v1104 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v1105 = Workspace:GetDescendants()
local v1106 = Workspace.Items:GetChildren()
local v1107 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v1108 = v1107.GetPivot(v1107)
v1104.CFrame = v1108
v1104.Anchored = true
task.wait(0.1)
local v1112 = v1107:FindFirstChild("Main")
local v1113 = v1112:FindFirstChild("ProximityAttachment")
local v1114 = v1113:FindFirstChild("ProximityInteraction")
tick()
v1104.Anchored = false
v1104.CFrame = v1104.CFrame
task.wait(1)
local v1119 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v1120 = Workspace:GetDescendants()
local v1121 = Workspace.Items:GetChildren()
local v1122 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v1123 = v1122.GetPivot(v1122)
v1119.CFrame = v1123
v1119.Anchored = true
task.wait(0.1)
local v1127 = v1122:FindFirstChild("Main")
local v1128 = v1127:FindFirstChild("ProximityAttachment")
local v1129 = v1128:FindFirstChild("ProximityInteraction")
tick()
v1119.Anchored = false
v1119.CFrame = v1119.CFrame
task.wait(1)
local v1134 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v1135 = Workspace:GetDescendants()
local v1136 = Workspace.Items:GetChildren()
local v1137 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v1138 = v1137.GetPivot(v1137)
v1134.CFrame = v1138
v1134.Anchored = true
task.wait(0.1)
local v1142 = v1137:FindFirstChild("Main")
local v1143 = v1142:FindFirstChild("ProximityAttachment")
local v1144 = v1143:FindFirstChild("ProximityInteraction")
tick()
v1134.Anchored = false
v1134.CFrame = v1134.CFrame
task.wait(1)
local v1149 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v1150 = Workspace:GetDescendants()
local v1151 = Workspace.Items:GetChildren()
local v1152 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v1153 = v1152.GetPivot(v1152)
v1149.CFrame = v1153
v1149.Anchored = true
task.wait(0.1)
local v1157 = v1152:FindFirstChild("Main")
local v1158 = v1157:FindFirstChild("ProximityAttachment")
local v1159 = v1158:FindFirstChild("ProximityInteraction")
tick()
v1149.Anchored = false
v1149.CFrame = v1149.CFrame
task.wait(1)
local v1164 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v1165 = Workspace:GetDescendants()
local v1166 = Workspace.Items:GetChildren()
local v1167 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v1168 = v1167.GetPivot(v1167)
v1164.CFrame = v1168
v1164.Anchored = true
task.wait(0.1)
local v1172 = v1167:FindFirstChild("Main")
local v1173 = v1172:FindFirstChild("ProximityAttachment")
local v1174 = v1173:FindFirstChild("ProximityInteraction")
tick()
v1164.Anchored = false
v1164.CFrame = v1164.CFrame
task.wait(1)
local v1179 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v1180 = Workspace:GetDescendants()
local v1181 = Workspace.Items:GetChildren()
local v1182 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v1183 = v1182.GetPivot(v1182)
v1179.CFrame = v1183
v1179.Anchored = true
task.wait(0.1)
local v1187 = v1182:FindFirstChild("Main")
local v1188 = v1187:FindFirstChild("ProximityAttachment")
local v1189 = v1188:FindFirstChild("ProximityInteraction")
tick()
v1179.Anchored = false
v1179.CFrame = v1179.CFrame
task.wait(1)
local v1194 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v1195 = Workspace:GetDescendants()
local v1196 = Workspace.Items:GetChildren()
local v1197 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v1198 = v1197.GetPivot(v1197)
v1194.CFrame = v1198
v1194.Anchored = true
task.wait(0.1)
local v1202 = v1197:FindFirstChild("Main")
local v1203 = v1202:FindFirstChild("ProximityAttachment")
local v1204 = v1203:FindFirstChild("ProximityInteraction")
tick()
v1194.Anchored = false
v1194.CFrame = v1194.CFrame
task.wait(1)
local v1209 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v1210 = Workspace:GetDescendants()
local v1211 = Workspace.Items:GetChildren()
local v1212 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v1213 = v1212.GetPivot(v1212)
v1209.CFrame = v1213
v1209.Anchored = true
task.wait(0.1)
local v1217 = v1212:FindFirstChild("Main")
local v1218 = v1217:FindFirstChild("ProximityAttachment")
local v1219 = v1218:FindFirstChild("ProximityInteraction")
tick()
v1209.Anchored = false
v1209.CFrame = v1209.CFrame
task.wait(1)
local v1224 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v1225 = Workspace:GetDescendants()
local v1226 = Workspace.Items:GetChildren()
local v1227 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v1228 = v1227.GetPivot(v1227)
v1224.CFrame = v1228
v1224.Anchored = true
task.wait(0.1)
local v1232 = v1227:FindFirstChild("Main")
local v1233 = v1232:FindFirstChild("ProximityAttachment")
local v1234 = v1233:FindFirstChild("ProximityInteraction")
tick()
v1224.Anchored = false
v1224.CFrame = v1224.CFrame
task.wait(1)
local v1239 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v1240 = Workspace:GetDescendants()
local v1241 = Workspace.Items:GetChildren()
local v1242 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v1243 = v1242.GetPivot(v1242)
v1239.CFrame = v1243
v1239.Anchored = true
task.wait(0.1)
local v1247 = v1242:FindFirstChild("Main")
local v1248 = v1247:FindFirstChild("ProximityAttachment")
local v1249 = v1248:FindFirstChild("ProximityInteraction")
tick()
v1239.Anchored = false
v1239.CFrame = v1239.CFrame
task.wait(1)
local v1254 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v1255 = Workspace:GetDescendants()
local v1256 = Workspace.Items:GetChildren()
local v1257 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v1258 = v1257.GetPivot(v1257)
v1254.CFrame = v1258
v1254.Anchored = true
task.wait(0.1)
local v1262 = v1257:FindFirstChild("Main")
local v1263 = v1262:FindFirstChild("ProximityAttachment")
local v1264 = v1263:FindFirstChild("ProximityInteraction")
tick()
v1254.Anchored = false
v1254.CFrame = v1254.CFrame
task.wait(1)
local v1269 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v1270 = Workspace:GetDescendants()
local v1271 = Workspace.Items:GetChildren()
local v1272 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v1273 = v1272.GetPivot(v1272)
v1269.CFrame = v1273
v1269.Anchored = true
task.wait(0.1)
local v1277 = v1272:FindFirstChild("Main")
local v1278 = v1277:FindFirstChild("ProximityAttachment")
local v1279 = v1278:FindFirstChild("ProximityInteraction")
tick()
v1269.Anchored = false
v1269.CFrame = v1269.CFrame
task.wait(1)
local v1284 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v1285 = Workspace:GetDescendants()
local v1286 = Workspace.Items:GetChildren()
local v1287 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v1288 = v1287.GetPivot(v1287)
v1284.CFrame = v1288
v1284.Anchored = true
task.wait(0.1)
local v1292 = v1287:FindFirstChild("Main")
local v1293 = v1292:FindFirstChild("ProximityAttachment")
local v1294 = v1293:FindFirstChild("ProximityInteraction")
tick()
v1284.Anchored = false
v1284.CFrame = v1284.CFrame
task.wait(1)
local v1299 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v1300 = Workspace:GetDescendants()
local v1301 = Workspace.Items:GetChildren()
local v1302 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v1303 = v1302.GetPivot(v1302)
v1299.CFrame = v1303
v1299.Anchored = true
task.wait(0.1)
local v1307 = v1302:FindFirstChild("Main")
local v1308 = v1307:FindFirstChild("ProximityAttachment")
local v1309 = v1308:FindFirstChild("ProximityInteraction")
tick()
v1299.Anchored = false
v1299.CFrame = v1299.CFrame
task.wait(1)
local v1314 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v1315 = Workspace:GetDescendants()
local v1316 = Workspace.Items:GetChildren()
local v1317 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v1318 = v1317.GetPivot(v1317)
v1314.CFrame = v1318
v1314.Anchored = true
task.wait(0.1)
local v1322 = v1317:FindFirstChild("Main")
local v1323 = v1322:FindFirstChild("ProximityAttachment")
local v1324 = v1323:FindFirstChild("ProximityInteraction")
tick()
v1314.Anchored = false
v1314.CFrame = v1314.CFrame
task.wait(1)
local v1329 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v1330 = Workspace:GetDescendants()
local v1331 = Workspace.Items:GetChildren()
local v1332 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v1333 = v1332.GetPivot(v1332)
v1329.CFrame = v1333
v1329.Anchored = true
task.wait(0.1)
local v1337 = v1332:FindFirstChild("Main")
local v1338 = v1337:FindFirstChild("ProximityAttachment")
local v1339 = v1338:FindFirstChild("ProximityInteraction")
tick()
v1329.Anchored = false
v1329.CFrame = v1329.CFrame
task.wait(1)
local v1344 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v1345 = Workspace:GetDescendants()
local v1346 = Workspace.Items:GetChildren()
local v1347 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v1348 = v1347.GetPivot(v1347)
v1344.CFrame = v1348
v1344.Anchored = true
task.wait(0.1)
local v1352 = v1347:FindFirstChild("Main")
local v1353 = v1352:FindFirstChild("ProximityAttachment")
local v1354 = v1353:FindFirstChild("ProximityInteraction")
tick()
v1344.Anchored = false
v1344.CFrame = v1344.CFrame
task.wait(1)
local v1359 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v1360 = Workspace:GetDescendants()
local v1361 = Workspace.Items:GetChildren()
local v1362 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v1363 = v1362.GetPivot(v1362)
v1359.CFrame = v1363
v1359.Anchored = true
task.wait(0.1)
local v1367 = v1362:FindFirstChild("Main")
local v1368 = v1367:FindFirstChild("ProximityAttachment")
local v1369 = v1368:FindFirstChild("ProximityInteraction")
tick()
v1359.Anchored = false
v1359.CFrame = v1359.CFrame
task.wait(1)
local v1374 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v1375 = Workspace:GetDescendants()
local v1376 = Workspace.Items:GetChildren()
local v1377 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v1378 = v1377.GetPivot(v1377)
v1374.CFrame = v1378
v1374.Anchored = true
task.wait(0.1)
local v1382 = v1377:FindFirstChild("Main")
local v1383 = v1382:FindFirstChild("ProximityAttachment")
local v1384 = v1383:FindFirstChild("ProximityInteraction")
tick()
v1374.Anchored = false
v1374.CFrame = v1374.CFrame
task.wait(1)
local v1389 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v1390 = Workspace:GetDescendants()
local v1391 = Workspace.Items:GetChildren()
local v1392 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v1393 = v1392.GetPivot(v1392)
v1389.CFrame = v1393
v1389.Anchored = true
task.wait(0.1)
local v1397 = v1392:FindFirstChild("Main")
local v1398 = v1397:FindFirstChild("ProximityAttachment")
local v1399 = v1398:FindFirstChild("ProximityInteraction")
tick()
v1389.Anchored = false
v1389.CFrame = v1389.CFrame
task.wait(1)
local v1404 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v1405 = Workspace:GetDescendants()
local v1406 = Workspace.Items:GetChildren()
local v1407 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v1408 = v1407.GetPivot(v1407)
v1404.CFrame = v1408
v1404.Anchored = true
task.wait(0.1)
local v1412 = v1407:FindFirstChild("Main")
local v1413 = v1412:FindFirstChild("ProximityAttachment")
local v1414 = v1413:FindFirstChild("ProximityInteraction")
tick()
v1404.Anchored = false
v1404.CFrame = v1404.CFrame
task.wait(1)
local v1419 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v1420 = Workspace:GetDescendants()
local v1421 = Workspace.Items:GetChildren()
local v1422 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v1423 = v1422.GetPivot(v1422)
v1419.CFrame = v1423
v1419.Anchored = true
task.wait(0.1)
local v1427 = v1422:FindFirstChild("Main")
local v1428 = v1427:FindFirstChild("ProximityAttachment")
local v1429 = v1428:FindFirstChild("ProximityInteraction")
tick()
v1419.Anchored = false
v1419.CFrame = v1419.CFrame
task.wait(1)
local v1434 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v1435 = Workspace:GetDescendants()
local v1436 = Workspace.Items:GetChildren()
local v1437 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v1438 = v1437.GetPivot(v1437)
v1434.CFrame = v1438
v1434.Anchored = true
task.wait(0.1)
local v1442 = v1437:FindFirstChild("Main")
local v1443 = v1442:FindFirstChild("ProximityAttachment")
local v1444 = v1443:FindFirstChild("ProximityInteraction")
tick()
v1434.Anchored = false
v1434.CFrame = v1434.CFrame
task.wait(1)
local v1449 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v1450 = Workspace:GetDescendants()
local v1451 = Workspace.Items:GetChildren()
local v1452 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v1453 = v1452.GetPivot(v1452)
v1449.CFrame = v1453
v1449.Anchored = true
task.wait(0.1)
local v1457 = v1452:FindFirstChild("Main")
local v1458 = v1457:FindFirstChild("ProximityAttachment")
local v1459 = v1458:FindFirstChild("ProximityInteraction")
tick()
v1449.Anchored = false
v1449.CFrame = v1449.CFrame
task.wait(1)
local v1464 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v1465 = Workspace:GetDescendants()
local v1466 = Workspace.Items:GetChildren()
local v1467 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v1468 = v1467.GetPivot(v1467)
v1464.CFrame = v1468
v1464.Anchored = true
task.wait(0.1)
local v1472 = v1467:FindFirstChild("Main")
local v1473 = v1472:FindFirstChild("ProximityAttachment")
local v1474 = v1473:FindFirstChild("ProximityInteraction")
tick()
v1464.Anchored = false
v1464.CFrame = v1464.CFrame
task.wait(1)
local v1479 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v1480 = Workspace:GetDescendants()
local v1481 = Workspace.Items:GetChildren()
local v1482 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v1483 = v1482.GetPivot(v1482)
v1479.CFrame = v1483
v1479.Anchored = true
task.wait(0.1)
local v1487 = v1482:FindFirstChild("Main")
local v1488 = v1487:FindFirstChild("ProximityAttachment")
local v1489 = v1488:FindFirstChild("ProximityInteraction")
tick()
v1479.Anchored = false
v1479.CFrame = v1479.CFrame
task.wait(1)
local v1494 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v1495 = Workspace:GetDescendants()
local v1496 = Workspace.Items:GetChildren()
local v1497 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v1498 = v1497.GetPivot(v1497)
v1494.CFrame = v1498
v1494.Anchored = true
task.wait(0.1)
local v1502 = v1497:FindFirstChild("Main")
local v1503 = v1502:FindFirstChild("ProximityAttachment")
local v1504 = v1503:FindFirstChild("ProximityInteraction")
tick()
v1494.Anchored = false
v1494.CFrame = v1494.CFrame
task.wait(1)
local v1509 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v1510 = Workspace:GetDescendants()
local v1511 = Workspace.Items:GetChildren()
local v1512 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v1513 = v1512.GetPivot(v1512)
v1509.CFrame = v1513
v1509.Anchored = true
task.wait(0.1)
local v1517 = v1512:FindFirstChild("Main")
local v1518 = v1517:FindFirstChild("ProximityAttachment")
local v1519 = v1518:FindFirstChild("ProximityInteraction")
tick()
v1509.Anchored = false
v1509.CFrame = v1509.CFrame
task.wait(1)
local v1524 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v1525 = Workspace:GetDescendants()
local v1526 = Workspace.Items:GetChildren()
local v1527 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v1528 = v1527.GetPivot(v1527)
v1524.CFrame = v1528
v1524.Anchored = true
task.wait(0.1)
local v1532 = v1527:FindFirstChild("Main")
local v1533 = v1532:FindFirstChild("ProximityAttachment")
local v1534 = v1533:FindFirstChild("ProximityInteraction")
tick()
v1524.Anchored = false
v1524.CFrame = v1524.CFrame
task.wait(1)
local v1539 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v1540 = Workspace:GetDescendants()
local v1541 = Workspace.Items:GetChildren()
local v1542 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v1543 = v1542.GetPivot(v1542)
v1539.CFrame = v1543
v1539.Anchored = true
task.wait(0.1)
local v1547 = v1542:FindFirstChild("Main")
local v1548 = v1547:FindFirstChild("ProximityAttachment")
local v1549 = v1548:FindFirstChild("ProximityInteraction")
tick()
v1539.Anchored = false
v1539.CFrame = v1539.CFrame
task.wait(1)
local v1554 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v1555 = Workspace:GetDescendants()
local v1556 = Workspace.Items:GetChildren()
local v1557 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v1558 = v1557.GetPivot(v1557)
v1554.CFrame = v1558
v1554.Anchored = true
task.wait(0.1)
local v1562 = v1557:FindFirstChild("Main")
local v1563 = v1562:FindFirstChild("ProximityAttachment")
local v1564 = v1563:FindFirstChild("ProximityInteraction")
tick()
v1554.Anchored = false
v1554.CFrame = v1554.CFrame
task.wait(1)
local v1569 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v1570 = Workspace:GetDescendants()
local v1571 = Workspace.Items:GetChildren()
local v1572 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v1573 = v1572.GetPivot(v1572)
v1569.CFrame = v1573
v1569.Anchored = true
task.wait(0.1)
local v1577 = v1572:FindFirstChild("Main")
local v1578 = v1577:FindFirstChild("ProximityAttachment")
local v1579 = v1578:FindFirstChild("ProximityInteraction")
tick()
v1569.Anchored = false
v1569.CFrame = v1569.CFrame
task.wait(1)
local v1584 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v1585 = Workspace:GetDescendants()
local v1586 = Workspace.Items:GetChildren()
local v1587 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v1588 = v1587.GetPivot(v1587)
v1584.CFrame = v1588
v1584.Anchored = true
task.wait(0.1)
local v1592 = v1587:FindFirstChild("Main")
local v1593 = v1592:FindFirstChild("ProximityAttachment")
local v1594 = v1593:FindFirstChild("ProximityInteraction")
tick()
v1584.Anchored = false
v1584.CFrame = v1584.CFrame
task.wait(1)
local v1599 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v1600 = Workspace:GetDescendants()
local v1601 = Workspace.Items:GetChildren()
local v1602 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v1603 = v1602.GetPivot(v1602)
v1599.CFrame = v1603
v1599.Anchored = true
task.wait(0.1)
local v1607 = v1602:FindFirstChild("Main")
local v1608 = v1607:FindFirstChild("ProximityAttachment")
local v1609 = v1608:FindFirstChild("ProximityInteraction")
tick()
v1599.Anchored = false
v1599.CFrame = v1599.CFrame
task.wait(1)
local v1614 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v1615 = Workspace:GetDescendants()
local v1616 = Workspace.Items:GetChildren()
local v1617 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v1618 = v1617.GetPivot(v1617)
v1614.CFrame = v1618
v1614.Anchored = true
task.wait(0.1)
local v1622 = v1617:FindFirstChild("Main")
local v1623 = v1622:FindFirstChild("ProximityAttachment")
local v1624 = v1623:FindFirstChild("ProximityInteraction")
tick()
v1614.Anchored = false
v1614.CFrame = v1614.CFrame
task.wait(1)
local v1629 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v1630 = Workspace:GetDescendants()
local v1631 = Workspace.Items:GetChildren()
local v1632 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v1633 = v1632.GetPivot(v1632)
v1629.CFrame = v1633
v1629.Anchored = true
task.wait(0.1)
local v1637 = v1632:FindFirstChild("Main")
local v1638 = v1637:FindFirstChild("ProximityAttachment")
local v1639 = v1638:FindFirstChild("ProximityInteraction")
tick()
v1629.Anchored = false
v1629.CFrame = v1629.CFrame
task.wait(1)
local v1644 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v1645 = Workspace:GetDescendants()
local v1646 = Workspace.Items:GetChildren()
local v1647 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v1648 = v1647.GetPivot(v1647)
v1644.CFrame = v1648
v1644.Anchored = true
task.wait(0.1)
local v1652 = v1647:FindFirstChild("Main")
local v1653 = v1652:FindFirstChild("ProximityAttachment")
local v1654 = v1653:FindFirstChild("ProximityInteraction")
tick()
v1644.Anchored = false
v1644.CFrame = v1644.CFrame
task.wait(1)
local v1659 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v1660 = Workspace:GetDescendants()
local v1661 = Workspace.Items:GetChildren()
local v1662 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v1663 = v1662.GetPivot(v1662)
v1659.CFrame = v1663
v1659.Anchored = true
task.wait(0.1)
local v1667 = v1662:FindFirstChild("Main")
local v1668 = v1667:FindFirstChild("ProximityAttachment")
local v1669 = v1668:FindFirstChild("ProximityInteraction")
tick()
v1659.Anchored = false
v1659.CFrame = v1659.CFrame
task.wait(1)
local v1674 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v1675 = Workspace:GetDescendants()
local v1676 = Workspace.Items:GetChildren()
local v1677 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v1678 = v1677.GetPivot(v1677)
v1674.CFrame = v1678
v1674.Anchored = true
task.wait(0.1)
local v1682 = v1677:FindFirstChild("Main")
local v1683 = v1682:FindFirstChild("ProximityAttachment")
local v1684 = v1683:FindFirstChild("ProximityInteraction")
tick()
v1674.Anchored = false
v1674.CFrame = v1674.CFrame
task.wait(1)
local v1689 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v1690 = Workspace:GetDescendants()
local v1691 = Workspace.Items:GetChildren()
local v1692 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v1693 = v1692.GetPivot(v1692)
v1689.CFrame = v1693
v1689.Anchored = true
task.wait(0.1)
local v1697 = v1692:FindFirstChild("Main")
local v1698 = v1697:FindFirstChild("ProximityAttachment")
local v1699 = v1698:FindFirstChild("ProximityInteraction")
tick()
v1689.Anchored = false
v1689.CFrame = v1689.CFrame
task.wait(1)
local v1704 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v1705 = Workspace:GetDescendants()
local v1706 = Workspace.Items:GetChildren()
local v1707 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v1708 = v1707.GetPivot(v1707)
v1704.CFrame = v1708
v1704.Anchored = true
task.wait(0.1)
local v1712 = v1707:FindFirstChild("Main")
local v1713 = v1712:FindFirstChild("ProximityAttachment")
local v1714 = v1713:FindFirstChild("ProximityInteraction")
tick()
v1704.Anchored = false
v1704.CFrame = v1704.CFrame
task.wait(1)
local v1719 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v1720 = Workspace:GetDescendants()
local v1721 = Workspace.Items:GetChildren()
local v1722 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v1723 = v1722.GetPivot(v1722)
v1719.CFrame = v1723
v1719.Anchored = true
task.wait(0.1)
local v1727 = v1722:FindFirstChild("Main")
local v1728 = v1727:FindFirstChild("ProximityAttachment")
local v1729 = v1728:FindFirstChild("ProximityInteraction")
tick()
v1719.Anchored = false
v1719.CFrame = v1719.CFrame
task.wait(1)
local v1734 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v1735 = Workspace:GetDescendants()
local v1736 = Workspace.Items:GetChildren()
local v1737 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v1738 = v1737.GetPivot(v1737)
v1734.CFrame = v1738
v1734.Anchored = true
task.wait(0.1)
local v1742 = v1737:FindFirstChild("Main")
local v1743 = v1742:FindFirstChild("ProximityAttachment")
local v1744 = v1743:FindFirstChild("ProximityInteraction")
tick()
v1734.Anchored = false
v1734.CFrame = v1734.CFrame
task.wait(1)
local v1749 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v1750 = Workspace:GetDescendants()
local v1751 = Workspace.Items:GetChildren()
local v1752 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v1753 = v1752.GetPivot(v1752)
v1749.CFrame = v1753
v1749.Anchored = true
task.wait(0.1)
local v1757 = v1752:FindFirstChild("Main")
local v1758 = v1757:FindFirstChild("ProximityAttachment")
local v1759 = v1758:FindFirstChild("ProximityInteraction")
tick()
v1749.Anchored = false
v1749.CFrame = v1749.CFrame
task.wait(1)
local v1764 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v1765 = Workspace:GetDescendants()
local v1766 = Workspace.Items:GetChildren()
local v1767 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v1768 = v1767.GetPivot(v1767)
v1764.CFrame = v1768
v1764.Anchored = true
task.wait(0.1)
local v1772 = v1767:FindFirstChild("Main")
local v1773 = v1772:FindFirstChild("ProximityAttachment")
local v1774 = v1773:FindFirstChild("ProximityInteraction")
tick()
v1764.Anchored = false
v1764.CFrame = v1764.CFrame
task.wait(1)
local v1779 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v1780 = Workspace:GetDescendants()
local v1781 = Workspace.Items:GetChildren()
local v1782 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v1783 = v1782.GetPivot(v1782)
v1779.CFrame = v1783
v1779.Anchored = true
task.wait(0.1)
local v1787 = v1782:FindFirstChild("Main")
local v1788 = v1787:FindFirstChild("ProximityAttachment")
local v1789 = v1788:FindFirstChild("ProximityInteraction")
tick()
v1779.Anchored = false
v1779.CFrame = v1779.CFrame
task.wait(1)
local v1794 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v1795 = Workspace:GetDescendants()
local v1796 = Workspace.Items:GetChildren()
local v1797 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v1798 = v1797.GetPivot(v1797)
v1794.CFrame = v1798
v1794.Anchored = true
task.wait(0.1)
local v1802 = v1797:FindFirstChild("Main")
local v1803 = v1802:FindFirstChild("ProximityAttachment")
local v1804 = v1803:FindFirstChild("ProximityInteraction")
tick()
v1794.Anchored = false
v1794.CFrame = v1794.CFrame
task.wait(1)
local v1809 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v1810 = Workspace:GetDescendants()
local v1811 = Workspace.Items:GetChildren()
local v1812 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v1813 = v1812.GetPivot(v1812)
v1809.CFrame = v1813
v1809.Anchored = true
task.wait(0.1)
local v1817 = v1812:FindFirstChild("Main")
local v1818 = v1817:FindFirstChild("ProximityAttachment")
local v1819 = v1818:FindFirstChild("ProximityInteraction")
tick()
v1809.Anchored = false
v1809.CFrame = v1809.CFrame
task.wait(1)
local v1824 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v1825 = Workspace:GetDescendants()
local v1826 = Workspace.Items:GetChildren()
local v1827 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v1828 = v1827.GetPivot(v1827)
v1824.CFrame = v1828
v1824.Anchored = true
task.wait(0.1)
local v1832 = v1827:FindFirstChild("Main")
local v1833 = v1832:FindFirstChild("ProximityAttachment")
local v1834 = v1833:FindFirstChild("ProximityInteraction")
tick()
v1824.Anchored = false
v1824.CFrame = v1824.CFrame
task.wait(1)
local v1839 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v1840 = Workspace:GetDescendants()
local v1841 = Workspace.Items:GetChildren()
local v1842 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v1843 = v1842.GetPivot(v1842)
v1839.CFrame = v1843
v1839.Anchored = true
task.wait(0.1)
local v1847 = v1842:FindFirstChild("Main")
local v1848 = v1847:FindFirstChild("ProximityAttachment")
local v1849 = v1848:FindFirstChild("ProximityInteraction")
tick()
v1839.Anchored = false
v1839.CFrame = v1839.CFrame
task.wait(1)
local v1854 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v1855 = Workspace:GetDescendants()
local v1856 = Workspace.Items:GetChildren()
local v1857 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v1858 = v1857.GetPivot(v1857)
v1854.CFrame = v1858
v1854.Anchored = true
task.wait(0.1)
local v1862 = v1857:FindFirstChild("Main")
local v1863 = v1862:FindFirstChild("ProximityAttachment")
local v1864 = v1863:FindFirstChild("ProximityInteraction")
tick()
v1854.Anchored = false
v1854.CFrame = v1854.CFrame
task.wait(1)
local v1869 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v1870 = Workspace:GetDescendants()
local v1871 = Workspace.Items:GetChildren()
local v1872 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v1873 = v1872.GetPivot(v1872)
v1869.CFrame = v1873
v1869.Anchored = true
task.wait(0.1)
local v1877 = v1872:FindFirstChild("Main")
local v1878 = v1877:FindFirstChild("ProximityAttachment")
local v1879 = v1878:FindFirstChild("ProximityInteraction")
tick()
v1869.Anchored = false
v1869.CFrame = v1869.CFrame
task.wait(1)
local v1884 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v1885 = Workspace:GetDescendants()
local v1886 = Workspace.Items:GetChildren()
local v1887 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v1888 = v1887.GetPivot(v1887)
v1884.CFrame = v1888
v1884.Anchored = true
task.wait(0.1)
local v1892 = v1887:FindFirstChild("Main")
local v1893 = v1892:FindFirstChild("ProximityAttachment")
local v1894 = v1893:FindFirstChild("ProximityInteraction")
tick()
v1884.Anchored = false
v1884.CFrame = v1884.CFrame
task.wait(1)
local v1899 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v1900 = Workspace:GetDescendants()
local v1901 = Workspace.Items:GetChildren()
local v1902 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v1903 = v1902.GetPivot(v1902)
v1899.CFrame = v1903
v1899.Anchored = true
task.wait(0.1)
local v1907 = v1902:FindFirstChild("Main")
local v1908 = v1907:FindFirstChild("ProximityAttachment")
local v1909 = v1908:FindFirstChild("ProximityInteraction")
tick()
v1899.Anchored = false
v1899.CFrame = v1899.CFrame
task.wait(1)
local v1914 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v1915 = Workspace:GetDescendants()
local v1916 = Workspace.Items:GetChildren()
local v1917 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v1918 = v1917.GetPivot(v1917)
v1914.CFrame = v1918
v1914.Anchored = true
task.wait(0.1)
local v1922 = v1917:FindFirstChild("Main")
local v1923 = v1922:FindFirstChild("ProximityAttachment")
local v1924 = v1923:FindFirstChild("ProximityInteraction")
tick()
v1914.Anchored = false
v1914.CFrame = v1914.CFrame
task.wait(1)
local v1929 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v1930 = Workspace:GetDescendants()
local v1931 = Workspace.Items:GetChildren()
local v1932 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v1933 = v1932.GetPivot(v1932)
v1929.CFrame = v1933
v1929.Anchored = true
task.wait(0.1)
local v1937 = v1932:FindFirstChild("Main")
local v1938 = v1937:FindFirstChild("ProximityAttachment")
local v1939 = v1938:FindFirstChild("ProximityInteraction")
tick()
v1929.Anchored = false
v1929.CFrame = v1929.CFrame
task.wait(1)
local v1944 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v1945 = Workspace:GetDescendants()
local v1946 = Workspace.Items:GetChildren()
local v1947 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v1948 = v1947.GetPivot(v1947)
v1944.CFrame = v1948
v1944.Anchored = true
task.wait(0.1)
local v1952 = v1947:FindFirstChild("Main")
local v1953 = v1952:FindFirstChild("ProximityAttachment")
local v1954 = v1953:FindFirstChild("ProximityInteraction")
tick()
v1944.Anchored = false
v1944.CFrame = v1944.CFrame
task.wait(1)
local v1959 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v1960 = Workspace:GetDescendants()
local v1961 = Workspace.Items:GetChildren()
local v1962 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v1963 = v1962.GetPivot(v1962)
v1959.CFrame = v1963
v1959.Anchored = true
task.wait(0.1)
local v1967 = v1962:FindFirstChild("Main")
local v1968 = v1967:FindFirstChild("ProximityAttachment")
local v1969 = v1968:FindFirstChild("ProximityInteraction")
tick()
v1959.Anchored = false
v1959.CFrame = v1959.CFrame
task.wait(1)
local v1974 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v1975 = Workspace:GetDescendants()
local v1976 = Workspace.Items:GetChildren()
local v1977 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v1978 = v1977.GetPivot(v1977)
v1974.CFrame = v1978
v1974.Anchored = true
task.wait(0.1)
local v1982 = v1977:FindFirstChild("Main")
local v1983 = v1982:FindFirstChild("ProximityAttachment")
local v1984 = v1983:FindFirstChild("ProximityInteraction")
tick()
v1974.Anchored = false
v1974.CFrame = v1974.CFrame
task.wait(1)
local v1989 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v1990 = Workspace:GetDescendants()
local v1991 = Workspace.Items:GetChildren()
local v1992 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v1993 = v1992.GetPivot(v1992)
v1989.CFrame = v1993
v1989.Anchored = true
task.wait(0.1)
local v1997 = v1992:FindFirstChild("Main")
local v1998 = v1997:FindFirstChild("ProximityAttachment")
local v1999 = v1998:FindFirstChild("ProximityInteraction")
tick()
v1989.Anchored = false
v1989.CFrame = v1989.CFrame
task.wait(1)
local v2004 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v2005 = Workspace:GetDescendants()
local v2006 = Workspace.Items:GetChildren()
local v2007 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v2008 = v2007.GetPivot(v2007)
v2004.CFrame = v2008
v2004.Anchored = true
task.wait(0.1)
local v2012 = v2007:FindFirstChild("Main")
local v2013 = v2012:FindFirstChild("ProximityAttachment")
local v2014 = v2013:FindFirstChild("ProximityInteraction")
tick()
v2004.Anchored = false
v2004.CFrame = v2004.CFrame
task.wait(1)
local v2019 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v2020 = Workspace:GetDescendants()
local v2021 = Workspace.Items:GetChildren()
local v2022 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v2023 = v2022.GetPivot(v2022)
v2019.CFrame = v2023
v2019.Anchored = true
task.wait(0.1)
local v2027 = v2022:FindFirstChild("Main")
local v2028 = v2027:FindFirstChild("ProximityAttachment")
local v2029 = v2028:FindFirstChild("ProximityInteraction")
tick()
v2019.Anchored = false
v2019.CFrame = v2019.CFrame
task.wait(1)
local v2034 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v2035 = Workspace:GetDescendants()
local v2036 = Workspace.Items:GetChildren()
local v2037 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v2038 = v2037.GetPivot(v2037)
v2034.CFrame = v2038
v2034.Anchored = true
task.wait(0.1)
local v2042 = v2037:FindFirstChild("Main")
local v2043 = v2042:FindFirstChild("ProximityAttachment")
local v2044 = v2043:FindFirstChild("ProximityInteraction")
tick()
v2034.Anchored = false
v2034.CFrame = v2034.CFrame
task.wait(1)
local v2049 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v2050 = Workspace:GetDescendants()
local v2051 = Workspace.Items:GetChildren()
local v2052 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v2053 = v2052.GetPivot(v2052)
v2049.CFrame = v2053
v2049.Anchored = true
task.wait(0.1)
local v2057 = v2052:FindFirstChild("Main")
local v2058 = v2057:FindFirstChild("ProximityAttachment")
local v2059 = v2058:FindFirstChild("ProximityInteraction")
tick()
v2049.Anchored = false
v2049.CFrame = v2049.CFrame
task.wait(1)
local v2064 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v2065 = Workspace:GetDescendants()
local v2066 = Workspace.Items:GetChildren()
local v2067 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v2068 = v2067.GetPivot(v2067)
v2064.CFrame = v2068
v2064.Anchored = true
task.wait(0.1)
local v2072 = v2067:FindFirstChild("Main")
local v2073 = v2072:FindFirstChild("ProximityAttachment")
local v2074 = v2073:FindFirstChild("ProximityInteraction")
tick()
v2064.Anchored = false
v2064.CFrame = v2064.CFrame
task.wait(1)
local v2079 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v2080 = Workspace:GetDescendants()
local v2081 = Workspace.Items:GetChildren()
local v2082 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v2083 = v2082.GetPivot(v2082)
v2079.CFrame = v2083
v2079.Anchored = true
task.wait(0.1)
local v2087 = v2082:FindFirstChild("Main")
local v2088 = v2087:FindFirstChild("ProximityAttachment")
local v2089 = v2088:FindFirstChild("ProximityInteraction")
tick()
v2079.Anchored = false
v2079.CFrame = v2079.CFrame
task.wait(1)
local v2094 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v2095 = Workspace:GetDescendants()
local v2096 = Workspace.Items:GetChildren()
local v2097 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v2098 = v2097.GetPivot(v2097)
v2094.CFrame = v2098
v2094.Anchored = true
task.wait(0.1)
local v2102 = v2097:FindFirstChild("Main")
local v2103 = v2102:FindFirstChild("ProximityAttachment")
local v2104 = v2103:FindFirstChild("ProximityInteraction")
tick()
v2094.Anchored = false
v2094.CFrame = v2094.CFrame
task.wait(1)
local v2109 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v2110 = Workspace:GetDescendants()
local v2111 = Workspace.Items:GetChildren()
local v2112 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v2113 = v2112.GetPivot(v2112)
v2109.CFrame = v2113
v2109.Anchored = true
task.wait(0.1)
local v2117 = v2112:FindFirstChild("Main")
local v2118 = v2117:FindFirstChild("ProximityAttachment")
local v2119 = v2118:FindFirstChild("ProximityInteraction")
tick()
v2109.Anchored = false
v2109.CFrame = v2109.CFrame
task.wait(1)
local v2124 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v2125 = Workspace:GetDescendants()
local v2126 = Workspace.Items:GetChildren()
local v2127 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v2128 = v2127.GetPivot(v2127)
v2124.CFrame = v2128
v2124.Anchored = true
task.wait(0.1)
local v2132 = v2127:FindFirstChild("Main")
local v2133 = v2132:FindFirstChild("ProximityAttachment")
local v2134 = v2133:FindFirstChild("ProximityInteraction")
tick()
v2124.Anchored = false
v2124.CFrame = v2124.CFrame
task.wait(1)
local v2139 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v2140 = Workspace:GetDescendants()
local v2141 = Workspace.Items:GetChildren()
local v2142 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v2143 = v2142.GetPivot(v2142)
v2139.CFrame = v2143
v2139.Anchored = true
task.wait(0.1)
local v2147 = v2142:FindFirstChild("Main")
local v2148 = v2147:FindFirstChild("ProximityAttachment")
local v2149 = v2148:FindFirstChild("ProximityInteraction")
tick()
v2139.Anchored = false
v2139.CFrame = v2139.CFrame
task.wait(1)
local v2154 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v2155 = Workspace:GetDescendants()
local v2156 = Workspace.Items:GetChildren()
local v2157 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v2158 = v2157.GetPivot(v2157)
v2154.CFrame = v2158
v2154.Anchored = true
task.wait(0.1)
local v2162 = v2157:FindFirstChild("Main")
local v2163 = v2162:FindFirstChild("ProximityAttachment")
local v2164 = v2163:FindFirstChild("ProximityInteraction")
tick()
v2154.Anchored = false
v2154.CFrame = v2154.CFrame
task.wait(1)
local v2169 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v2170 = Workspace:GetDescendants()
local v2171 = Workspace.Items:GetChildren()
local v2172 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v2173 = v2172.GetPivot(v2172)
v2169.CFrame = v2173
v2169.Anchored = true
task.wait(0.1)
local v2177 = v2172:FindFirstChild("Main")
local v2178 = v2177:FindFirstChild("ProximityAttachment")
local v2179 = v2178:FindFirstChild("ProximityInteraction")
tick()
v2169.Anchored = false
v2169.CFrame = v2169.CFrame
task.wait(1)
local v2184 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v2185 = Workspace:GetDescendants()
local v2186 = Workspace.Items:GetChildren()
local v2187 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v2188 = v2187.GetPivot(v2187)
v2184.CFrame = v2188
v2184.Anchored = true
task.wait(0.1)
local v2192 = v2187:FindFirstChild("Main")
local v2193 = v2192:FindFirstChild("ProximityAttachment")
local v2194 = v2193:FindFirstChild("ProximityInteraction")
tick()
v2184.Anchored = false
v2184.CFrame = v2184.CFrame
task.wait(1)
local v2199 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v2200 = Workspace:GetDescendants()
local v2201 = Workspace.Items:GetChildren()
local v2202 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v2203 = v2202.GetPivot(v2202)
v2199.CFrame = v2203
v2199.Anchored = true
task.wait(0.1)
local v2207 = v2202:FindFirstChild("Main")
local v2208 = v2207:FindFirstChild("ProximityAttachment")
local v2209 = v2208:FindFirstChild("ProximityInteraction")
tick()
v2199.Anchored = false
v2199.CFrame = v2199.CFrame
task.wait(1)
local v2214 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v2215 = Workspace:GetDescendants()
local v2216 = Workspace.Items:GetChildren()
local v2217 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v2218 = v2217.GetPivot(v2217)
v2214.CFrame = v2218
v2214.Anchored = true
task.wait(0.1)
local v2222 = v2217:FindFirstChild("Main")
local v2223 = v2222:FindFirstChild("ProximityAttachment")
local v2224 = v2223:FindFirstChild("ProximityInteraction")
tick()
v2214.Anchored = false
v2214.CFrame = v2214.CFrame
task.wait(1)
local v2229 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v2230 = Workspace:GetDescendants()
local v2231 = Workspace.Items:GetChildren()
local v2232 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v2233 = v2232.GetPivot(v2232)
v2229.CFrame = v2233
v2229.Anchored = true
task.wait(0.1)
local v2237 = v2232:FindFirstChild("Main")
local v2238 = v2237:FindFirstChild("ProximityAttachment")
local v2239 = v2238:FindFirstChild("ProximityInteraction")
tick()
v2229.Anchored = false
v2229.CFrame = v2229.CFrame
task.wait(1)
local v2244 = game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
local v2245 = Workspace:GetDescendants()
local v2246 = Workspace.Items:GetChildren()
local v2247 = Workspace.Items:FindFirstChild("Stronghold Diamond Chest")
local v2248 = v2247.GetPivot(v2247)
v2244.CFrame = v2248
v2244.Anchored = true
task.wait(0.1)
local v2252 = v2247:FindFirstChild("Main")
local v2253 = v2252:FindFirstChild("ProximityAttachment")
local v2254 = v2253:FindFirstChild("ProximityInteraction")
tick()
v2244.Anchored = false
v2244.CFrame = v2244.CFrame
error("/app/GalacticDumper/dumper/dumper.lua:36: Too Much Operations...")
